### ISSUE TITLE
Area object scale 

### ISSUE THREAD

**Issue by Someone-some** [shibbo/Takochu#10]
Loading 0 as the scale in all 3 dimensions for area objects, and therefore when saving, the scale for area objects is saved as 0.

**Game** Both. 

**To reproduce**  Open a Galaxy that has a area object in it and select it. 

**Expected behaviour** Successfully load the scale values from the BCSV.

I didn't make any changes I just selected the area. 
![Screenshot (145)](https://user-images.githubusercontent.com/78685823/109289955-e0c08f00-781e-11eb-9ef0-12ab7d70feed.png)

Same area in whitehole. 
![Screenshot (147)](https://user-images.githubusercontent.com/78685823/109290171-2da46580-781f-11eb-97e4-885fb00038d2.png)

OS: Windows 10 
Browser: Chrome 
Version: Windows: 10.0.18363 Build 18363 Chrome: 88.0.4324.190 Takochu: commit e89105b

**Comment by shibbo** [comment]
fixed with 4161073
