### ISSUE TITLE
Cameras frozen in place

### ISSUE THREAD

**Issue by Someone-some** [shibbo/Takochu#11]
Cameras are frozen in place just focused on the player. 

**Game** SMG2

**to reproduce** open a galaxy, click save then play the galaxy. Cameras should be frozen in place. This is a problem with SaveObjects(p.Key, "Placement", "CameraCubeInfo");

**expected behaviour** Cameras to follow player unless specified to not to.

![Screenshot (154)](https://user-images.githubusercontent.com/78685823/109568833-62464480-7adf-11eb-9a82-a753c9b9283f.png)
![Screenshot (156)](https://user-images.githubusercontent.com/78685823/109568856-6bcfac80-7adf-11eb-8a22-11f1749b3489.png)

OS: Windows 10

**Comment by shibbo** [comment]
possibly fixed with 035c8ff? needs further testing

**Comment by shibbo** [comment]
issue has been confirmed fixed by 035c8ff
