### ISSUE TITLE
zoneListView is not being cleared

### ISSUE THREAD

**Issue by Someone-some** [shibbo/Takochu#12]
**Describe the bug**
zoneListview isn't cleared when selecting scenarios 

** Game **
both

**To Reproduce**
open a galaxy select a scenario then select a different scenario 

**Expected behavior**
zoneListView needs clearing when selecting scenarios otherwise it tries to add items that already exist 

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Chrome
 - Version Takochu commit 3a9abee

**Comment by shibbo** [comment]
fixed with 764bc66
