### ISSUE TITLE
mFilesystem is not closed when closing the RARC explorer

### ISSUE THREAD

**Issue by Someone-some** [shibbo/Takochu#13]
**Describe the bug**
mFilesystem is not closed when closing the RARC explorer form.

**Game**
Both

**To Reproduce**
Open the RARC explorer, open a RARC, close the RARC explorer, open the BCSV editor, open the same RARC.

**Expected behaviour**
self explanatory but anyway, mFilesystem needs to be closed when closing the rarc explorer form 

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mandar1jn** [comment]
From what I can see it is. Am I missing something?
![7FA5D900-653A-437A-9671-D09A0204931F](https://user-images.githubusercontent.com/49076509/111884574-ce231b00-89c2-11eb-8f70-f122cb55f908.png)

**Comment by Someone-some** [comment]
Huh that is so weird I still get a IO exception saying the file is in use 
![Screenshot (1)](https://user-images.githubusercontent.com/78685823/111884975-da0bde80-89bc-11eb-81c6-37d3e302202e.png)

but adding a form closing event to the rarc explorer and doing 
  if (mFilesystem != null)
           mFilesystem.Close();
fixes it

**Comment by shibbo** [comment]
fixed with be86866
