### ISSUE TITLE
Green stars crash the scenario editor 

### ISSUE THREAD

**Issue by Someone-some** [shibbo/Takochu#15]
**Describe the bug**
Having a green star selected crashes the scenario editor 

** Game **
SMG2 

**To Reproduce**
Select a green star scenario then click the scenario editor button 

**Screenshots**
quick fix I wrote
![Screenshot (20)](https://user-images.githubusercontent.com/78685823/113108027-75daed00-91fc-11eb-805a-ebcbab2406fd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by shibbo** [comment]
fixed with 0a8706d
