### ISSUE TITLE
lights UI bug 

### ISSUE THREAD

**Issue by Someone-some** [shibbo/Takochu#16]
**Describe the bug**
the Object UI control in the lights tab isn't anchored to top so its in the wrong place when in full screen

** Game **
SMG2

**To Reproduce**
Open a galaxy, select a scenario, go to the lights tab and select a entry

**Expected behavior**
I never know what to put here but the UI control should be directly under the lights list view not half way down the screen

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by shibbo** [comment]
fixed with 70df8df
