### ISSUE TITLE
Error message after opening game files for use. Unable to run exe afterwards.

### ISSUE THREAD

**Issue by JohnALAN275** [shibbo/Takochu#17]
OS: Windows 10 x64 Version 20H2
Release version: 0.2

**Comment by shibbo** [comment]
I don't have enough information to really solve this issue. Tell me what error you get?

**Comment by JohnALAN275** [comment]
![Desktop Screenshot 2021 04 27 - 13 59 42 59](https://user-images.githubusercontent.com/83169849/116245501-ed029300-a760-11eb-9e9f-c630b99ffdb5.png)
This happens when selecting the file directory.

**Comment by ruffaldabaoth** [comment]
That’s an error with your Super Mario Galaxy files. It looks like it’s trying to find SystemMessage.arc. Do you have it in your folder?

**Comment by JohnALAN275** [comment]
i have verified my game files and everything is intact. it was an issue with identifying folder structures that are isolated to different regions. my copy is pal so when it tried to find ntsc localizedata it was looking for a non existent folder. it can be fixed by making takochu look for pal folders as well as ntsc

**Comment by shibbo** [comment]
All of my tests were USA, so that does explain the issues. I will have Takochu automatically detect the region and load the according files, but that won't be until tomorrow.

**Comment by shibbo** [comment]
@JohnALAN275 try using commit 81c43eb

**Comment by shibbo** [comment]
closed due to inactivity
