### ISSUE TITLE
ScenarioInfoEditor crash 

### ISSUE THREAD

**Issue by Someone-some** [shibbo/Takochu#20]
**Describe the bug**
ScenarioInfoEditor crashes due to scenarioEntry being null.

** Game **
SMG2 

**To Reproduce**
open Spin-Dig Galaxy select scenario 2 and click the ScenarioEditor button. This may happen with other stages but I haven't tested all of them.

**Expected behavior**
not really sure what I should put here. It not to crash I guess.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by shibbo** [comment]
fixed in 25d0b71
