### ISSUE TITLE
ScenarioEditor crash 

### ISSUE THREAD

**Issue by Someone-some** [shibbo/Takochu#21]
**Describe the bug**
ScenarioEditor crashes if a GalaxyInfoTexture BTI doesn't exist

** Game **
SMG2

**To Reproduce**
open a galaxy that doesn't have a GalaxyInfoTexture like the starship and click the ScenarioInfoEditor button

**Screenshots**
simple fix just check if a BTI exists for that stage
![Screenshot (94)](https://user-images.githubusercontent.com/78685823/118334993-91792900-b506-11eb-995f-8a0f5f725721.png)
 

**Desktop (please complete the following information):**

**Comment by shibbo** [comment]
fixed in 25d0b71
