### ISSUE TITLE
Layer Mask Error

### ISSUE THREAD

**Issue by AwesomeTMC** [shibbo/Takochu#34]
**Describe the bug**
When selecting certain galaxies, like JungleGliderGalaxy it gives an error.

**Game**
SMG2, probably also happens in SMG1

**To Reproduce**
Open up JungleGliderGalaxy(any galaxy probably works though), click Stage Information, and select a zone from the layer mask

**Expected behavior**
It lets you edit the layer masks.

**Screenshots**
![image](https://user-images.githubusercontent.com/38051573/150698753-7af51874-f7f2-469b-b7ef-8007f6cfb063.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Latest update)

**Comment by penguin117117** [comment]
Does the same thing happen if I select a zone after selecting the left scenario in the relevant window?

**Comment by penguin117117** [comment]
> **Describe the bug** When selecting certain galaxies, like JungleGliderGalaxy it gives an error.
> 
> **Game** SMG2, probably also happens in SMG1
> 
> **To Reproduce** Open up JungleGliderGalaxy(any galaxy probably works though), click Stage Information, and select a zone from the layer mask
> 
> **Expected behavior** It lets you edit the layer masks.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/38051573/150698753-7af51874-f7f2-469b-b7ef-8007f6cfb063.png)
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Windows 10 (Latest update)

Does the same thing happen if I select a zone after selecting the left scenario in the relevant window?

**Comment by shibbo** [comment]
fixed with 6c87b242
