### ISSUE TITLE
Failing to grab lights 

### ISSUE THREAD

**Issue by Someone-some** [shibbo/Takochu#9]
![Screenshot (142)](https://user-images.githubusercontent.com/78685823/109225232-e84b4e00-77b4-11eb-8c45-d0c000874304.png)
![Screenshot (141)](https://user-images.githubusercontent.com/78685823/109225250-ee412f00-77b4-11eb-9310-519e22c262fe.png)

**Comment by shibbo** [comment]
fixed with e89105b
